#include "cache.h"
#include "fuzz-cmd-base.h"


/*
 * This function is used to randomize the content of a file with the
 * random data. The random data normally come from the fuzzing engine
 * LibFuzzer in order to create randomization of the git file worktree
 * and possibly messing up of certain git config file to fuzz different
 * git command execution logic.
 */
void randomize_git_file(char *dir, char *name, char *data_chunk, int data_size) {
   char fname[256];
   FILE *fp;

   snprintf(fname, 255, "%s/%s", dir, name);

   fp = fopen(fname, "wb");
   if (fp) {
      fwrite(data_chunk, 1, data_size, fp);
      fclose(fp);
   }
}

/*
 * This function is the variants of the above functions which takes
 * in a set of target files to be processed. These target file are
 * passing to the above function one by one for content rewrite.
 */
void randomize_git_files(char *dir, char *name_set[], int files_count, char *data, int size) {
   int data_size = size / files_count;

   for(int i=0; i<files_count; i++) {
      char *data_chunk = malloc(data_size);
      memcpy(data_chunk, data + (i * data_size), data_size);

      randomize_git_file(dir, name_set[i], data_chunk, data_size);

      free(data_chunk);
   }
}

/*
 * Instead of randomizing the content of existing files. This helper
 * function helps generate a temp file with random file name before
 * passing to the above functions to get randomized content for later
 * fuzzing of git command
 */
void generate_random_file(char *data, int size) {
   unsigned char *hash = malloc(size);
   char *fname = malloc((size*2)+12);
   char *data_chunk = malloc(size);

   memcpy(hash, data, size);
   memcpy(data_chunk, data + size, size);

   snprintf(fname, size*2+11, "TEMP-%s-TEMP", hash_to_hex(hash));
   randomize_git_file(".", fname, data_chunk, size);

   free(hash);
   free(fname);
   free(data_chunk);
}

/*
 * This function helps to generate random commit and build up a
 * worktree with randomization to provide a target for the fuzzing
 * of git commands.
 */
void generate_commit(char *data, int size) {
   int ret = 0;
   char *data_chunk = malloc(size * 2);
   memcpy(data_chunk, data, size * 2);

   generate_random_file(data_chunk, size);
   ret += system("git add TEMP-*-TEMP");
   ret += system("git commit -m\"New Commit\"");

   free(data_chunk);
}

/*
 * In some cases, there maybe some fuzzing logic that will mess
 * up with the git repository and its configuration and settings.
 * This function aims to reset the git repository into the default
 * base settings before each round of fuzzing.
 */
int reset_git_folder(void) {
   int ret = 0;

   ret += system("rm -rf ./.git");
   ret += system("rm -f ./TEMP-*-TEMP");
   ret += system("git init");
   ret += system("git config --global user.name \"FUZZ\"");
   ret += system("git config --global user.email \"FUZZ@LOCALHOST\"");
   ret += system("git config --global --add safe.directory '*'");
   ret += system("git add ./TEMP_1 ./TEMP_2");
   ret += system("git commit -m\"First Commit\"");

   return ret;
}

/*
 * This helper function returns the maximum number of commit can
 * be generated by the provided random data without reusing the
 * data to increase randomization of the fuzzing target and allow
 * more path of fuzzing to be covered.
 */
int get_max_commit_count(int data_size, int git_files_count, int hash_size) {
   int count = (data_size - 4 - git_files_count * 2) / (hash_size * 2);

   if(count > 20) {
      count = 20;
   }

   return count;
}
