#!/bin/bash

want() {
	git for-each-ref --format='%(refname:short)' refs/heads refs/tags |
	tr / . |
	sort -u
}

comm -23 <(Meta/install/versions) <(want) |
while read cruft; do
	dir=$HOME/local/git/$cruft
	echo >&2 "Removing $dir..."
	rm -rf "$dir"
done
